name: CI

on: [push, pull_request]

jobs:
  linux:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]

    steps:
    - uses: actions/checkout@v2
    - name: Install bake
      run: |
        git clone https://github.com/SanderMertens/bake
        make -C bake/build-$(uname)
        bake/bake setup

    - name: Build Flecs
      run: bake --strict

    - name: Build Flecs (release)
      run: bake --cfg release

    - name: Build examples
      run: |
        bake examples/c
        bake examples/cpp
         
    - name: Run tests
      run: |
        bake examples/os_api/flecs-os_api-bake
        bake test

  macos:
    timeout-minutes: 20
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install bake
      run: |
        git clone https://github.com/SanderMertens/bake
        make -C bake/build-$(uname)
        bake/bake setup

    - name: Build Flecs
      run: bake --strict

    - name: Build Flecs (release)
      run: bake --cfg release
         
    - name: Run tests
      run: |
        bake examples/os_api/flecs-os_api-bake
        bake test

  windows:
    timeout-minutes: 10
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Install bake
      run: |
        git clone https://github.com/SanderMertens/bake
        cd bake\build-Windows
        nmake
        cd ..
        ./bake setup --local

    - name: Build Flecs
      run: bake/bake --strict

    - name: Run tests
      run: |
        bake/bake examples/os_api/flecs-os_api-bake
        bake/bake run test\base

  sanitizer:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest]
        compiler: [clang]

    steps:
    - uses: actions/checkout@v2
    - name: Install bake
      run: |
        git clone https://github.com/SanderMertens/bake
        make -C bake/build-$(uname)
        bake/bake setup
        
    - name: Build Flecs
      run: bake --strict

    - name: Run tests
      run: |
        bake examples/os_api/flecs-os_api-bake
        bake run test/base --cfg sanitize

  amalgamated:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
        compiler: [gcc, clang]    
    
    steps:
    - uses: actions/checkout@v2
    - name: Build Flecs
      run: ${{ matrix.compiler }} flecs.c --shared -fPIC -pedantic -Wall -Wextra -Wno-unused-parameter -Werror -Wshadow -Wconversion -Wno-missing-field-initializers
